"""Generate docs/anti-slop-reference.md from registry/anti-slop.json."""

from __future__ import annotations

import json
from pathlib import Path

REGISTRY_PATH = Path(__file__).parent.parent.parent / "registry" / "anti-slop.json"
OUTPUT_PATH = Path(__file__).parent.parent.parent / "docs" / "anti-slop-reference.md"


def render(target_path: Path | None = None) -> Path:
    """Render the markdown anti-slop reference from the registry."""
    target = target_path or OUTPUT_PATH

    if not REGISTRY_PATH.exists():
        raise FileNotFoundError(f"Registry not found: {REGISTRY_PATH}")

    with open(REGISTRY_PATH) as f:
        registry = json.load(f)

    rules = registry.get("rules", [])
    lines = [
        "# Anti-Slop Pattern Reference",
        "",
        "> GENERATED BY NIO from `registry/anti-slop.json`. Do not edit manually.",
        "",
        f"**{len(rules)} patterns** across three tiers.",
        "",
    ]

    for tier in ["critical", "context", "natural"]:
        tier_rules = [r for r in rules if r["tier"] == tier]
        if not tier_rules:
            continue

        lines.append(f"## {tier.title()} ({len(tier_rules)} rules)")
        lines.append("")

        for rule in tier_rules:
            lines.append(f"### {rule['id']}")
            lines.append(f"**{rule['description']}** | Action: `{rule.get('action', 'warn')}` | Severity: {rule.get('severity', 1)}")
            lines.append("")

            examples = rule.get("examples", {})
            bad = examples.get("bad", [])
            good = examples.get("good", [])

            if bad:
                lines.append("Bad:")
                for b in bad:
                    lines.append(f"- `{b}`")
            if good:
                lines.append("Good:")
                for g in good:
                    lines.append(f"- `{g}`")
            lines.append("")

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines))
    return target
