"""Generate TypeScript anti-slop validator from registry/anti-slop.json."""

from __future__ import annotations

import json
from pathlib import Path

REGISTRY_PATH = Path(__file__).parent.parent.parent / "registry" / "anti-slop.json"
DEFAULT_TS_TARGET = Path.home() / "treadit" / "src" / "lib" / "ai" / "anti-slop.ts"


def _escape_ts_string(s: str) -> str:
    """Escape a string for use in a TypeScript template literal."""
    return s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def render(target_path: Path | None = None) -> Path:
    """Render the TypeScript anti-slop module from the registry."""
    target = target_path or DEFAULT_TS_TARGET

    if not REGISTRY_PATH.exists():
        raise FileNotFoundError(f"Registry not found: {REGISTRY_PATH}")

    with open(REGISTRY_PATH) as f:
        registry = json.load(f)

    rules = registry.get("rules", [])
    regex_rules = [r for r in rules if r.get("matcher", {}).get("type") == "regex"]

    lines = [
        "// GENERATED BY NIO: DO NOT EDIT MANUALLY",
        "// Source: registry/anti-slop.json",
        f"// Rules: {len(regex_rules)} regex + {len(rules) - len(regex_rules)} structural",
        "// Edit the registry, then run: nio antislop sync",
        "",
        "export interface SlopRule {",
        "  id: string;",
        "  tier: 'critical' | 'context' | 'natural';",
        "  description: string;",
        "  pattern: RegExp;",
        "  action: 'replace' | 'delete' | 'warn' | 'allow';",
        "  replacement?: string;",
        "  severity: number;",
        "}",
        "",
        "export const SLOP_RULES: SlopRule[] = [",
    ]

    for rule in regex_rules:
        matcher = rule["matcher"]
        pattern = _escape_ts_string(matcher.get("pattern", ""))
        flags = matcher.get("flags", "")
        # Ensure 'g' flag is present for matchAll behavior
        if "g" not in flags:
            flags += "g"

        action = rule.get("action", "warn")
        replacement = rule.get("replacement")

        lines.append("  {")
        lines.append(f"    id: '{rule['id']}',")
        lines.append(f"    tier: '{rule['tier']}',")
        lines.append(f"    description: `{_escape_ts_string(rule['description'])}`,")
        lines.append(f"    pattern: new RegExp(`{pattern}`, '{flags}'),")
        lines.append(f"    action: '{action}',")
        if replacement is not None:
            lines.append(f"    replacement: `{_escape_ts_string(replacement)}`,")
        lines.append(f"    severity: {rule.get('severity', 1)},")
        lines.append("  },")

    lines.extend([
        "];",
        "",
        "export interface Detection {",
        "  id: string;",
        "  tier: string;",
        "  description: string;",
        "  action: string;",
        "  severity: number;",
        "  matches: string[];",
        "  count: number;",
        "}",
        "",
        "export function detect(text: string): Detection[] {",
        "  const detections: Detection[] = [];",
        "  for (const rule of SLOP_RULES) {",
        "    const matches = text.match(rule.pattern);",
        "    if (matches && matches.length > 0) {",
        "      detections.push({",
        "        id: rule.id,",
        "        tier: rule.tier,",
        "        description: rule.description,",
        "        action: rule.action,",
        "        severity: rule.severity,",
        "        matches: matches.slice(0, 5),",
        "        count: matches.length,",
        "      });",
        "    }",
        "  }",
        "  return detections;",
        "}",
        "",
        "export function score(text: string): number {",
        "  const detections = detect(text);",
        "  if (detections.length === 0) return 100;",
        "  const weights: Record<string, number> = { critical: 3, context: 1.5, natural: 0 };",
        "  const tokens = Math.max(text.split(/\\s+/).length, 1);",
        "  let penalty = 0;",
        "  for (const d of detections) {",
        "    const w = weights[d.tier] ?? 1;",
        "    penalty += d.severity * w * d.count;",
        "  }",
        "  return Math.max(0, Math.min(100, 100 - (penalty / tokens) * 100));",
        "}",
        "",
        "// Treadit compatibility: re-export with legacy interface",
        "export interface AntiSlopResult {",
        "  score: number;",
        "  violations: string[];",
        "  fixedText: string;",
        "}",
        "",
        "export function validateAntiSlop(text: string): AntiSlopResult {",
        "  const detections = detect(text);",
        "  const violations = detections.map(",
        "    (d) => `${d.description}: ${d.count} occurrence(s)`",
        "  );",
        "  let fixed = text;",
        "  for (const rule of SLOP_RULES) {",
        "    if (rule.action === 'replace' && rule.replacement !== undefined) {",
        "      fixed = fixed.replace(rule.pattern, rule.replacement);",
        "    } else if (rule.action === 'delete' && rule.replacement !== undefined) {",
        "      fixed = fixed.replace(rule.pattern, rule.replacement);",
        "    }",
        "  }",
        "  // Clean up artifacts from auto-fixes",
        "  fixed = fixed.replace(/ {2,}/g, ' ');",
        "  fixed = fixed.replace(/\\n{3,}/g, '\\n\\n');",
        "  fixed = fixed.replace(/^\\.\\s*$/gm, '');",
        "  fixed = fixed.replace(/^\\s+$/gm, '');",
        "  fixed = fixed.trim();",
        "  return { score: score(text), violations, fixedText: fixed };",
        "}",
        "",
    ])

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines))
    return target
