"""Generate nio/core/antislop.py from registry/anti-slop.json.

Bakes patterns inline so the runtime module has zero file-system dependencies.
The generated module still supports runtime registry loading as a fallback.
"""

from __future__ import annotations

import json
from pathlib import Path

REGISTRY_PATH = Path(__file__).parent.parent.parent / "registry" / "anti-slop.json"
OUTPUT_PATH = Path(__file__).parent.parent / "core" / "antislop.py"


def render(target_path: Path | None = None) -> Path:
    """Render the Python anti-slop validator from the registry."""
    target = target_path or OUTPUT_PATH

    if not REGISTRY_PATH.exists():
        raise FileNotFoundError(f"Registry not found: {REGISTRY_PATH}")

    with open(REGISTRY_PATH) as f:
        registry = json.load(f)

    rules = registry.get("rules", [])
    # Only include regex-based rules for codegen
    regex_rules = [r for r in rules if r.get("matcher", {}).get("type") == "regex"]

    lines = [
        '"""Anti-slop validator.',
        "",
        "GENERATED BY NIO: DO NOT EDIT MANUALLY",
        "Source: registry/anti-slop.json",
        f"Rules: {len(regex_rules)} regex + {len(rules) - len(regex_rules)} structural",
        "",
        "Edit the registry, then run: nio antislop sync",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import json",
        "import re",
        "from pathlib import Path",
        "from typing import Optional",
        "",
        "",
        "# Baked-in rules from registry (generated at sync time)",
        "RULES: list[dict] = [",
    ]

    for rule in regex_rules:
        matcher = rule["matcher"]
        lines.append("    {")
        lines.append(f'        "id": {json.dumps(rule["id"])},')
        lines.append(f'        "tier": {json.dumps(rule["tier"])},')
        lines.append(f'        "description": {json.dumps(rule["description"])},')
        lines.append(f'        "pattern": {json.dumps(matcher["pattern"])},')
        lines.append(f'        "flags": {json.dumps(matcher.get("flags", ""))},')
        lines.append(f'        "action": {json.dumps(rule.get("action", "warn"))},')
        replacement = rule.get("replacement")
        if replacement is None:
            lines.append('        "replacement": None,')
        else:
            lines.append(f'        "replacement": {json.dumps(replacement)},')
        lines.append(f'        "severity": {rule.get("severity", 1)},')
        lines.append("    },")

    lines.extend([
        "]",
        "",
        "",
        "# Fallback: load from registry file if available",
        "REGISTRY_PATH = Path(__file__).parent.parent.parent / \"registry\" / \"anti-slop.json\"",
        "_registry_cache: Optional[dict] = None",
        "",
        "",
        "def _get_rules() -> list[dict]:",
        '    """Return baked-in rules. Falls back to registry file if RULES is empty."""',
        "    if RULES:",
        "        return RULES",
        "    global _registry_cache",
        "    if _registry_cache is not None:",
        '        return [r for r in _registry_cache.get("rules", []) if r.get("matcher", {}).get("type") == "regex"]',
        "    if REGISTRY_PATH.exists():",
        "        with open(REGISTRY_PATH) as f:",
        "            _registry_cache = json.load(f)",
        '        return [r for r in _registry_cache.get("rules", []) if r.get("matcher", {}).get("type") == "regex"]',
        "    return []",
        "",
        "",
        "def _compile_flags(flags_str: str) -> int:",
        '    """Convert flag string to re flags."""',
        "    flags = 0",
        '    if "i" in flags_str:',
        "        flags |= re.IGNORECASE",
        '    if "m" in flags_str:',
        "        flags |= re.MULTILINE",
        "    return flags",
        "",
        "",
        "def detect(text: str) -> list[dict]:",
        '    """Detect slop patterns in text. Returns list of detection dicts."""',
        "    detections = []",
        "    for rule in _get_rules():",
        '        pattern = rule.get("pattern", "")',
        "        if not pattern:",
        "            continue",
        '        flags = _compile_flags(rule.get("flags", ""))',
        "        try:",
        "            matches = re.findall(pattern, text, flags)",
        "        except re.error:",
        "            continue",
        "        if matches:",
        "            str_matches = [",
        "                m if isinstance(m, str) else m[0] if isinstance(m, tuple) else str(m)",
        "                for m in matches",
        "            ]",
        "            detections.append({",
        '                "id": rule["id"],',
        '                "tier": rule["tier"],',
        '                "description": rule["description"],',
        '                "action": rule.get("action", "warn"),',
        '                "severity": rule.get("severity", 1),',
        '                "matches": str_matches[:5],',
        '                "count": len(matches),',
        "            })",
        "    return detections",
        "",
        "",
        "def score(text: str) -> float:",
        '    """Score text for slop (0-100, higher = cleaner).',
        "",
        "    Formula:",
        "        score = 100 - sum(severity * weight_by_tier) / normalized_token_count * 100",
        "        weight_by_tier = { critical: 3, context: 1.5, natural: 0 }",
        "        Clamped to [0, 100]",
        '    """',
        "    detections = detect(text)",
        "    if not detections:",
        "        return 100.0",
        "",
        '    weight_by_tier = {"critical": 3.0, "context": 1.5, "natural": 0.0}',
        "    token_count = max(len(text.split()), 1)",
        "",
        "    penalty = 0.0",
        "    for d in detections:",
        '        tier_weight = weight_by_tier.get(d["tier"], 1.0)',
        '        penalty += d["severity"] * tier_weight * d["count"]',
        "",
        "    normalized = penalty / token_count * 100",
        "    return max(0.0, min(100.0, 100.0 - normalized))",
    ])

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines) + "\n")
    return target
