"""Anti-slop validator.

GENERATED BY NIO: DO NOT EDIT MANUALLY
Source: registry/anti-slop.json
Rules: 27 regex + 2 structural

Edit the registry, then run: nio antislop sync
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Optional


# Baked-in rules from registry (generated at sync time)
RULES: list[dict] = [
    {
        "id": "em_dashes",
        "tier": "critical",
        "description": "Em-dash abuse. Delete all. Use periods, commas, or restructure.",
        "pattern": "\\u2014+",
        "flags": "g",
        "action": "replace",
        "replacement": ". ",
        "severity": 3,
    },
    {
        "id": "en_dashes",
        "tier": "critical",
        "description": "En-dash abuse. Same treatment as em-dashes.",
        "pattern": "\\u2013+",
        "flags": "g",
        "action": "replace",
        "replacement": ". ",
        "severity": 2,
    },
    {
        "id": "authority_signaling",
        "tier": "critical",
        "description": "Authority signaling phrases. Delete the setup, state directly.",
        "pattern": "\\b(?:[Tt]he uncomfortable truth|[Ll]et me be clear|[Hh]ere'?s what nobody tells you|[Tt]he hard truth is|[Hh]ere'?s the reality|[Ww]hat most people miss(?:\\s+is)?)\\b",
        "flags": "gi",
        "action": "delete",
        "replacement": "",
        "severity": 3,
    },
    {
        "id": "narrator_setup",
        "tier": "critical",
        "description": "Narrator setup lines. Delete the setup, start with the actual point.",
        "pattern": "\\b(?:[Hh]ere'?s the thing about|[Hh]ere'?s where it gets interesting|[Hh]ere'?s the real (?:value|story|reason)|[Hh]ere'?s the actual |[Tt]he real (?:story|question|issue) is)\\b",
        "flags": "gi",
        "action": "delete",
        "replacement": "",
        "severity": 3,
    },
    {
        "id": "dramatic_rhetorical",
        "tier": "critical",
        "description": "Dramatic rhetorical framing. State what happened. Let the reader feel it.",
        "pattern": "\\b(?:[Bb]ut here'?s the part where|[Aa]nd that'?s when it clicked|[Ww]ant to know the crazy part)\\b",
        "flags": "gi",
        "action": "delete",
        "replacement": "",
        "severity": 2,
    },
    {
        "id": "bookend_summary",
        "tier": "critical",
        "description": "Opening thesis restated at the end. Real thinking goes somewhere new by the end.",
        "pattern": "\\b[Ii]n (?:summary|conclusion|short),?\\s",
        "flags": "gi",
        "action": "delete",
        "replacement": "",
        "severity": 2,
    },
    {
        "id": "self_branded_concepts",
        "tier": "critical",
        "description": "Self-branded concepts. Just explain it.",
        "pattern": "\\b(?:[Tt]his is what [Ii] call|[Ii] like to call this|[Ww]hat [Ii] refer to as)\\b",
        "flags": "gi",
        "action": "delete",
        "replacement": "",
        "severity": 2,
    },
    {
        "id": "artificial_drama",
        "tier": "critical",
        "description": "Artificial drama sentences. Show why it's hard with a specific example.",
        "pattern": "[Tt]he shift sounds simple\\.\\s*[Ii]t'?s not\\.|[Ss]ounds easy\\.\\s*[Ii]t isn'?t\\.",
        "flags": "g",
        "action": "warn",
        "replacement": None,
        "severity": 2,
    },
    {
        "id": "colon_lists",
        "tier": "critical",
        "description": "Colon-listed everything. Reads like a PowerPoint slide. Write natural sentences.",
        "pattern": "\\b(?:the )?(?:result|impact|answer|truth|lesson|takeaway):",
        "flags": "gi",
        "action": "warn",
        "replacement": None,
        "severity": 2,
    },
    {
        "id": "humble_brag",
        "tier": "critical",
        "description": "Humble brag disclaimer. Share your take or don't. The disclaimer makes it worse.",
        "pattern": "\\b(?:[Ii] don'?t have all the answers,? but|[Ii]'?m no expert,? but|[Nn]ot to brag,? but)\\b",
        "flags": "gi",
        "action": "delete",
        "replacement": "",
        "severity": 2,
    },
    {
        "id": "hype_words",
        "tier": "critical",
        "description": "Lazy energy words that say nothing. Replace with what actually changed or happened.",
        "pattern": "\\b(?:game[\\s-]?changer|chaos|unleash|supercharge|next[\\s-]?level|revolutionize|transform(?:ative)?)\\b",
        "flags": "gi",
        "action": "delete",
        "replacement": "",
        "severity": 3,
    },
    {
        "id": "no_fluff_disclaimers",
        "tier": "critical",
        "description": "Saying 'no fluff' is itself fluff. If the content has no fluff, the reader will know.",
        "pattern": "\\b[Nn]o (?:fluff|BS|bs|b\\.s\\.|nonsense)\\b",
        "flags": "gi",
        "action": "delete",
        "replacement": "",
        "severity": 2,
    },
    {
        "id": "nada_filler",
        "tier": "critical",
        "description": "Performative emphasis that reads as AI padding. Cut it.",
        "pattern": "\\bnada\\b",
        "flags": "gi",
        "action": "delete",
        "replacement": "",
        "severity": 1,
    },
    {
        "id": "sycophantic_openers",
        "tier": "critical",
        "description": "Sycophantic openers that signal AI-generated responses.",
        "pattern": "(?:[Gg]reat question!|[Aa]bsolutely!|[Dd]efinitely!|[Oo]f course!)",
        "flags": "g",
        "action": "delete",
        "replacement": "",
        "severity": 2,
    },
    {
        "id": "self_referential_openers",
        "tier": "critical",
        "description": "Opens with YOU instead of VALUE. The reader doesn't care about your process.",
        "pattern": "^(?:[Dd]ropping|[Ss]haring) (?:this|these|a|my|something)\\b",
        "flags": "gm",
        "action": "warn",
        "replacement": None,
        "severity": 1,
    },
    {
        "id": "announcement_without_value",
        "tier": "critical",
        "description": "Announcement-style title with no value proposition.",
        "pattern": "\\bis (?:live|here|out|ready)\\.\\s*$",
        "flags": "gim",
        "action": "warn",
        "replacement": None,
        "severity": 1,
    },
    {
        "id": "false_drama_ellipsis",
        "tier": "critical",
        "description": "Ellipsis used to build false suspense before a common word.",
        "pattern": "\\.{3,}\\s*(?:here|and|but|the)",
        "flags": "gi",
        "action": "replace",
        "replacement": ". ",
        "severity": 2,
    },
    {
        "id": "hedging_transitions",
        "tier": "critical",
        "description": "Overused transition phrases that signal AI-generated structure.",
        "pattern": "\\b[Tt]hat (?:said|being said),?\\s",
        "flags": "g",
        "action": "delete",
        "replacement": "",
        "severity": 1,
    },
    {
        "id": "filler_transitions",
        "tier": "critical",
        "description": "Filler transition phrases that add nothing.",
        "pattern": "\\b[Ww]ithout further ado\\b",
        "flags": "g",
        "action": "delete",
        "replacement": "",
        "severity": 1,
    },
    {
        "id": "engagement_bait",
        "tier": "context",
        "description": "Engagement bait endings. Generally avoid, but OK on meme posts.",
        "pattern": "\\b(?:[Ss]o here'?s my question for you|[Ww]hat do you think\\?|[Cc]urious to hear your thoughts|[Dd]rop a comment)\\b",
        "flags": "gi",
        "action": "warn",
        "replacement": None,
        "severity": 1,
    },
    {
        "id": "false_dichotomies",
        "tier": "context",
        "description": "False dichotomies. Avoid, but legitimate old-vs-new contrasts are fine.",
        "pattern": "[Ii]t'?s not \\w+,\\s*it'?s \\w+",
        "flags": "g",
        "action": "warn",
        "replacement": None,
        "severity": 1,
    },
    {
        "id": "bold_headers_as_transitions",
        "tier": "context",
        "description": "Headers for navigation only. LinkedIn formatting is whitespace-driven.",
        "pattern": "\\*\\*[^*]+\\*\\*(?=\\s*[A-Z])",
        "flags": "g",
        "action": "warn",
        "replacement": None,
        "severity": 1,
    },
    {
        "id": "quotation_overuse",
        "tier": "context",
        "description": "Quoted phrases that don't need quotes. Write them as plain text.",
        "pattern": "\"[^\"]{5,}\"",
        "flags": "g",
        "action": "warn",
        "replacement": None,
        "severity": 1,
    },
    {
        "id": "ellipses_trailing",
        "tier": "natural",
        "description": "Ellipses for trailing thoughts. Part of natural voice.",
        "pattern": "\\.{3}",
        "flags": "g",
        "action": "allow",
        "replacement": None,
        "severity": 0,
    },
    {
        "id": "workflow_arrows",
        "tier": "natural",
        "description": "Arrows for workflow steps and progression. Part of natural voice.",
        "pattern": "(?:-->|\u27a1\ufe0f|\u2192)",
        "flags": "g",
        "action": "allow",
        "replacement": None,
        "severity": 0,
    },
    {
        "id": "emoji_section_markers",
        "tier": "natural",
        "description": "Emoji section markers for structuring workflow walkthroughs.",
        "pattern": "[\u2705\ud83d\udd27\ud83d\udd17\ud83e\udde0\ud83d\udd77\ufe0f]",
        "flags": "g",
        "action": "allow",
        "replacement": None,
        "severity": 0,
    },
    {
        "id": "directional_heres",
        "tier": "natural",
        "description": "Directional 'here's how/the play' openers. Part of natural voice, not narrator setup.",
        "pattern": "\\b(?:[Hh]ere'?s how|[Hh]ere'?s the play)\\b",
        "flags": "g",
        "action": "allow",
        "replacement": None,
        "severity": 0,
    },
]


# Fallback: load from registry file if available
REGISTRY_PATH = Path(__file__).parent.parent.parent / "registry" / "anti-slop.json"
_registry_cache: Optional[dict] = None


def _get_rules() -> list[dict]:
    """Return baked-in rules. Falls back to registry file if RULES is empty."""
    if RULES:
        return RULES
    global _registry_cache
    if _registry_cache is not None:
        return [r for r in _registry_cache.get("rules", []) if r.get("matcher", {}).get("type") == "regex"]
    if REGISTRY_PATH.exists():
        with open(REGISTRY_PATH) as f:
            _registry_cache = json.load(f)
        return [r for r in _registry_cache.get("rules", []) if r.get("matcher", {}).get("type") == "regex"]
    return []


def _compile_flags(flags_str: str) -> int:
    """Convert flag string to re flags."""
    flags = 0
    if "i" in flags_str:
        flags |= re.IGNORECASE
    if "m" in flags_str:
        flags |= re.MULTILINE
    return flags


def load_registry() -> list[dict]:
    """Return the full anti-slop rule set (baked-in + any registry file overlay)."""
    return _get_rules()


def detect(text: str) -> list[dict]:
    """Detect slop patterns in text. Returns list of detection dicts."""
    detections = []
    for rule in _get_rules():
        pattern = rule.get("pattern", "")
        if not pattern:
            continue
        flags = _compile_flags(rule.get("flags", ""))
        try:
            matches = re.findall(pattern, text, flags)
        except re.error:
            continue
        if matches:
            str_matches = [
                m if isinstance(m, str) else m[0] if isinstance(m, tuple) else str(m)
                for m in matches
            ]
            detections.append({
                "id": rule["id"],
                "tier": rule["tier"],
                "description": rule["description"],
                "action": rule.get("action", "warn"),
                "severity": rule.get("severity", 1),
                "matches": str_matches[:5],
                "count": len(matches),
            })
    return detections


def score(text: str) -> float:
    """Score text for slop (0-100, higher = cleaner).

    Formula:
        score = 100 - sum(severity * weight_by_tier) / normalized_token_count * 100
        weight_by_tier = { critical: 3, context: 1.5, natural: 0 }
        Clamped to [0, 100]
    """
    detections = detect(text)
    if not detections:
        return 100.0

    weight_by_tier = {"critical": 3.0, "context": 1.5, "natural": 0.0}
    token_count = max(len(text.split()), 1)

    penalty = 0.0
    for d in detections:
        tier_weight = weight_by_tier.get(d["tier"], 1.0)
        penalty += d["severity"] * tier_weight * d["count"]

    normalized = penalty / token_count * 100
    return max(0.0, min(100.0, 100.0 - normalized))
